name: "rewriteReadme"
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Issue List in README
      uses: seed-of-apricot/issue-list-readme@v1.1.0
            
